version: '3.8'

services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      - VITE_URL=http://host.docker.internal:5001
    networks:
      - cipherballot-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - server

  server:
    build: ./server
    ports:
      - "5001:5001"
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
    networks:
      - cipherballot-network

networks:
  cipherballot-network:
    driver: bridge