version: '3'

services:
  # React client service
  client:
    build:
      context: ./client  # Set the build context to the current directory
      dockerfile: Dockerfile  # Specify the Dockerfile for the React app
      args:
        - API_URL=${http://18.206.123.190:5001:-http://localhost:5001}
    ports:
      - "3000:3000"  # Expose React app on port 3000
    networks:
      - app_network

  # Flask server service
  server:
    build:
      context: ./server  # Set the build context to the current directory
      dockerfile: Dockerfile  # Specify the Dockerfile for the Flask server
    ports:
      - "5001:5001"  # Expose Flask app on port 5001
    networks:
      - app_network
    environment:
      - FLASK_APP=app.py  # Set environment variable for Flask app
      - FLASK_RUN_HOST=0.0.0.0  # Ensure Flask listens on all interfaces

networks:
  app_network:
    driver: bridge
