version: '3.8'

services:
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://server:5001
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server
    networks:
      - cipherballot-network
    restart: unless-stopped

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - PYTHONPATH=/app
    volumes:
      - ./server:/app
      - /app/__pycache__
    command: gunicorn --bind 0.0.0.0:5001 app:application
    networks:
      - cipherballot-network
    restart: unless-stopped

networks:
  cipherballot-network:
    driver: bridge